version: "3"

services:
  database:
    image: postgres #como postgres já é uma imagem dafault no dockerhub não precisa de um Dockefile
    container_name: work-wave-container-database
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER} #usuario do banco de dados
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD} #senha do banco de dados
      - POSTGRES_DB=${POSTGRES_DB_NAME} #nome do banco de dados
    ports:
      - ${POSTGRES_DB_PORT}:5432
    volumes:
      - postgres-data:/data/postgres
    networks:
      - database-network
  backend:
    container_name: work-wave-container-backend
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "npm run dev"
    environment:
      - NODE_ENV=dev
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    networks:
      - database-network

volumes:
  postgres-data:

networks:
  database-network:
    driver: bridge
